"""Symbolic design for the length-four reversal intervention; no model execution.

Every position is a zero-based *content* position. An adapter adds the BOS offset.
The two candidates concern an address-only intervention, not whole-state copying.
Families share one compiled program and vocabulary: fresh families test new token
assignments, not transfer to independent programs. Production confirmation is only
generated by an explicit call after the operator freezes its contract.
"""
from dataclasses import asdict, dataclass
from hashlib import sha256
from itertools import combinations
import json
import math
import random
from typing import Iterable, Sequence, Tuple

from causal_decidability.compatible_set import compatible_set, groups_of


VOCABULARY = tuple(range(12))
CANDIDATES = ("address", "donor_answer")
DEV_SEED = 2026092901
CONFIRMATION_SEED = 2026092902
# Ten distinct token roles, with the two discriminator answers unordered.
FAMILY_POPULATION_SIZE = math.factorial(12) // math.factorial(2) // 2
STAGES = ("shared", "discriminator", "followup")


def _integer(value, label):
    if isinstance(value, bool) or not isinstance(value, int):
        raise ValueError(f"{label} must be an integer")


def _tokens(values, label):
    values = tuple(values)
    if len(values) != 4:
        raise ValueError(f"{label} must have exactly four content tokens")
    for value in values:
        _integer(value, label)
        if value not in VOCABULARY:
            raise ValueError(f"{label} tokens must belong to the fixed vocabulary")
    if len(set(values)) != 4:
        raise ValueError(f"{label} content tokens must be distinct")
    return values


@dataclass(frozen=True)
class Case:
    case_id: str
    family_id: str
    stage: str
    recipient: Tuple[int, ...]
    donor: Tuple[int, ...]
    source_query: int = 1
    target_query: int = 0

    def __post_init__(self):
        if not self.case_id or not self.family_id or self.stage not in STAGES:
            raise ValueError("case and family IDs and a declared stage are required")
        object.__setattr__(self, "recipient", _tokens(self.recipient, "recipient"))
        object.__setattr__(self, "donor", _tokens(self.donor, "donor"))
        _integer(self.source_query, "source_query")
        _integer(self.target_query, "target_query")
        if (self.source_query, self.target_query) != (1, 0):
            raise ValueError("this contract fixes source_query=1 and target_query=0")
        address_answer = self.recipient[self.address]
        donor_answer = self.donor[self.address]
        if self.stage == "shared" and address_answer != donor_answer:
            raise ValueError("shared-stage candidate predictions must coincide")
        if self.stage != "shared" and address_answer == donor_answer:
            raise ValueError("discriminator and followup predictions must differ")
        if self.recipient[self.native_index] in (address_answer, donor_answer):
            raise ValueError("native unchanged-output null must differ from both candidates")

    @property
    def address(self):
        return len(self.donor) - 1 - self.source_query

    @property
    def native_index(self):
        return len(self.recipient) - 1 - self.target_query

    @property
    def signature(self):
        return (self.recipient, self.donor, self.source_query, self.target_query)

    def to_dict(self):
        result = asdict(self)
        result.update(address=self.address, native_index=self.native_index,
                      source_model_position=self.source_query + 1,
                      target_model_position=self.target_query + 1)
        return result


@dataclass(frozen=True)
class Family:
    family_id: str
    split: str
    seed: int
    shared: Case
    discriminators: Tuple[Case, ...]
    followups: Tuple[Case, ...]

    def __post_init__(self):
        if self.split not in ("development", "confirmation"):
            raise ValueError("unknown family split")
        _integer(self.seed, "seed")
        object.__setattr__(self, "discriminators", tuple(self.discriminators))
        object.__setattr__(self, "followups", tuple(self.followups))
        if len(self.discriminators) != 2 or len(self.followups) != 2:
            raise ValueError("declare exactly two discriminator/followup pairs")
        cases = (self.shared,) + tuple(self.discriminators) + tuple(self.followups)
        if any(case.family_id != self.family_id for case in cases):
            raise ValueError("all cases must belong to the declared family")
        if len({case.case_id for case in cases}) != len(cases):
            raise ValueError("case IDs must be unique")
        if self.shared.stage != "shared":
            raise ValueError("family must begin with the shared stage")
        for discriminator, followup in zip(self.discriminators, self.followups):
            if discriminator.stage != "discriminator" or followup.stage != "followup":
                raise ValueError("family stages are out of order")
            if discriminator.recipient != self.shared.recipient:
                raise ValueError("discriminator must preserve the shared recipient")
            if any(discriminator.donor[i] != self.shared.donor[i] for i in (0, 1, 3)):
                raise ValueError("discriminator may change only donor content at address 2")
            if followup.donor != discriminator.donor:
                raise ValueError("followup must preserve the selected discriminator donor")
            if any(followup.recipient[i] != discriminator.recipient[i] for i in (0, 1, 3)):
                raise ValueError("followup may change only recipient content at address 2")
        if self.followups[0].recipient != self.followups[1].recipient:
            raise ValueError("both choices must share the same fresh recipient")
        roles = (self.shared.recipient + tuple(self.shared.donor[i] for i in (0, 1, 3))
                 + tuple(case.donor[2] for case in self.discriminators)
                 + (self.followups[0].recipient[2],))
        if len(set(roles)) != 10:
            raise ValueError("all ten token roles must be distinct except the shared answer")

    @property
    def signature(self):
        """Content identity, invariant to split, seed, ID and allowed-menu ordering."""
        pairs = sorted((a.signature, b.signature)
                       for a, b in zip(self.discriminators, self.followups))
        payload = json.dumps((self.shared.signature, pairs), separators=(",", ":"))
        return sha256(payload.encode("utf-8")).hexdigest()

    def followup_for(self, discriminator_case_id):
        for discriminator, followup in zip(self.discriminators, self.followups):
            if discriminator.case_id == discriminator_case_id:
                return followup
        raise ValueError("followup requires an allowed discriminator case ID")

    def to_dict(self):
        return dict(family_id=self.family_id, split=self.split, seed=self.seed,
                    signature=self.signature, shared=self.shared.to_dict(),
                    discriminators=[case.to_dict() for case in self.discriminators],
                    followups=[case.to_dict() for case in self.followups])


def generate_families(count, *, seed, split, excluded_families=()):
    """Sample unique families deterministically, excluding declared earlier families.

    The seed is mandatory. Confirmation requires the complete development family
    collection so both IDs and content signatures can be audited for disjointness.
    Rejection uses only symbolic content; no outcome, model or score is consulted.
    Uniqueness makes this sampling without replacement from the token-assignment
    population. A literal iid binomial interpretation therefore needs a separate
    justification; it is not supplied by this deterministic generator.
    """
    _integer(count, "count")
    _integer(seed, "seed")
    if count <= 0 or seed < 0 or split not in ("development", "confirmation"):
        raise ValueError("positive count, nonnegative seed and known split required")
    excluded_families = tuple(excluded_families)
    if split == "development" and seed == CONFIRMATION_SEED:
        raise ValueError("production confirmation seed is reserved")
    if split == "confirmation" and (not excluded_families or seed == DEV_SEED):
        raise ValueError("confirmation requires excluded development families and a fresh seed")
    if split == "confirmation" and not any(f.split == "development" for f in excluded_families):
        raise ValueError("excluded_families must include the development collection")
    if split == "confirmation" and any(f.seed == seed for f in excluded_families):
        raise ValueError("confirmation seed must differ from excluded family seeds")
    used_ids = {family.family_id for family in excluded_families}
    used_signatures = {family.signature for family in excluded_families}
    rng, result = random.Random(seed), []
    for draw in range(max(1000, 100 * count)):
        a, b, c, d, w, x, z, y1, y2, u = rng.sample(VOCABULARY, 10)
        y1, y2 = sorted((y1, y2))
        family_id = f"{split}-{seed}-{draw:06d}"
        shared = Case(f"{family_id}/shared", family_id, "shared", (a, b, c, d), (w, x, c, z))
        discriminators, followups = [], []
        for choice, answer in enumerate((y1, y2)):
            donor = (w, x, answer, z)
            discriminators.append(Case(f"{family_id}/discriminator-{choice}", family_id,
                                       "discriminator", (a, b, c, d), donor))
            followups.append(Case(f"{family_id}/followup-{choice}", family_id,
                                  "followup", (a, b, u, d), donor))
        family = Family(family_id, split, seed, shared, tuple(discriminators), tuple(followups))
        if family_id in used_ids or family.signature in used_signatures:
            continue
        result.append(family)
        used_ids.add(family_id)
        used_signatures.add(family.signature)
        if len(result) == count:
            return tuple(result)
    raise ValueError("could not generate enough disjoint families within the declared draw budget")


def one_hot(token):
    _integer(token, "token")
    if token not in VOCABULARY:
        raise ValueError("token is outside the fixed output vocabulary")
    return tuple(float(value == token) for value in VOCABULARY)


def predictions(case):
    """Fixed candidate equations, with vectors in VOCABULARY order."""
    return {"address": one_hot(case.recipient[case.address]),
            "donor_answer": one_hot(case.donor[case.address])}


def native_prediction(case):
    """Unchanged recipient answer, a separate null control, not a candidate."""
    return one_hot(case.recipient[case.native_index])


@dataclass(frozen=True)
class Tolerance:
    """Readout coordinate bounds; no stochastic/Gaussian noise model is assumed.

    scientific_tolerance is the declared acceptable departure from a one-hot
    endpoint. numeric_allowance must be supplied from development calibration by
    the caller, recorded separately, and frozen before confirmation. This class
    validates values; it cannot establish that calibration actually happened.
    """
    scientific_tolerance: float
    numeric_allowance: float

    def __post_init__(self):
        for value in (self.scientific_tolerance, self.numeric_allowance):
            if isinstance(value, bool) or not isinstance(value, (int, float)):
                raise ValueError("tolerances must be finite nonnegative numbers")
            if not math.isfinite(value) or value < 0:
                raise ValueError("tolerances must be finite nonnegative numbers")
        if not self.radius < 0.5:
            raise ValueError("total coordinate radius must be strictly less than 0.5")

    @property
    def radius(self):
        return self.scientific_tolerance + self.numeric_allowance


def select_discriminator(family, retained, tolerance, *, used_case_ids=(), equivalence_groups=()):
    """Prediction-only menu selection: most separated group pairs, then case ID.

    All menu entries cost one additional intervention condition; qualification
    forwards are accounted separately by the runner. Separation requires disjoint
    radius boxes for every member pair across declared equivalence groups. The
    only outcome-derived input is the current compatible candidate set; measured
    scores, decoded outputs, reference labels and adapter sites are not accepted.
    """
    retained = tuple(retained)
    if len(set(retained)) != len(retained) or set(retained) - set(CANDIDATES):
        raise ValueError("retained must be a subset of the declared candidates")
    declared_groups = groups_of(CANDIDATES, equivalence_groups)
    if any(set(group) & set(retained) and not set(group) <= set(retained)
           for group in declared_groups):
        raise ValueError("retained set must preserve declared equivalence groups")
    groups = [group for group in declared_groups if set(group) <= set(retained)]
    allowed_ids = {case.case_id for case in family.discriminators}
    used_case_ids = set(used_case_ids)
    if used_case_ids - allowed_ids:
        raise ValueError("used_case_ids contains an undeclared discriminator")
    menu = []
    for case in sorted(family.discriminators, key=lambda item: item.case_id):
        pred = predictions(case)
        separated = sum(all(max(abs(x - y) for x, y in zip(pred[a], pred[b]))
                            > 2 * tolerance.radius for a in left for b in right)
                        for left, right in combinations(groups, 2))
        menu.append(dict(case_id=case.case_id, predictions=pred, separated_pairs=separated,
                         cost_units=1, available=case.case_id not in used_case_ids))
    eligible = [item for item in menu if item["available"] and item["separated_pairs"] > 0]
    selected = min(eligible, key=lambda item: (-item["separated_pairs"], item["case_id"])) if eligible else None
    reason = ("maximum separated group pairs per equal-cost condition; case-ID tie break"
              if selected else "no retained rival pair separable by an unused allowed condition")
    return dict(selected_case_id=selected["case_id"] if selected else None,
                reason=reason, menu=menu, retained=list(retained))


def cumulative_retention(cases: Iterable[Case], observations: Iterable[Sequence[float]],
                         tolerance: Tolerance, *, controls_passed: bool,
                         equivalence_groups=()):
    """Return each prefix's compatibility decision over all its output coordinates.

    This is a deterministic bounded-residual comparison, not repeated confidence
    testing. Invalid measurements/qualification raise; they never become evidence
    against a candidate. Inputs must be one family's shared stage, followed by up
    to two distinct allowed discriminator cases and an optional matching followup.
    Absolute population adequacy is a separate family-level confirmation analysis.
    """
    if controls_passed is not True:
        raise ValueError("intervention qualification failed or was not explicitly confirmed")
    cases, observations = tuple(cases), tuple(observations)
    if not cases or len(cases) != len(observations):
        raise ValueError("one complete score vector is required per nonempty case sequence")
    if len({case.family_id for case in cases}) != 1 or len({case.case_id for case in cases}) != len(cases):
        raise ValueError("trajectory requires unique cases from exactly one family")
    if cases[0].stage != "shared" or len(cases) > 4:
        raise ValueError("trajectory starts with shared and has at most four measurements")
    if any(case.stage == "shared" for case in cases[1:]):
        raise ValueError("shared stage may occur only first")
    followups = [index for index, case in enumerate(cases) if case.stage == "followup"]
    if followups and (followups != [len(cases) - 1] or len(cases) < 3):
        raise ValueError("a followup must be last and follow a discriminator")
    if followups and cases[-1].donor != cases[-2].donor:
        raise ValueError("followup donor must match the preceding discriminator")
    shared = cases[0]
    for case in cases[1:]:
        if any(case.donor[index] != shared.donor[index] for index in (0, 1, 3)):
            raise ValueError("trajectory must preserve donor background tokens")
        if case.stage == "discriminator" and case.recipient != shared.recipient:
            raise ValueError("discriminator must preserve the shared recipient")
        if case.stage == "followup":
            if (any(case.recipient[index] != shared.recipient[index] for index in (0, 1, 3))
                    or case.recipient[2] == shared.recipient[2]):
                raise ValueError("followup must change exactly recipient content at address 2")
    rows, measured, trajectory = {name: [] for name in CANDIDATES}, [], []
    retained = sorted(CANDIDATES)
    for case, observation in zip(cases, observations):
        observation = tuple(observation)
        if len(observation) != len(VOCABULARY):
            raise ValueError("measurement must contain every fixed-vocabulary output score")
        if any(isinstance(value, bool) or not isinstance(value, (int, float))
               or not math.isfinite(value) for value in observation):
            raise ValueError("non-finite or nonnumeric score is an invalid measurement")
        pred = predictions(case)
        for name in CANDIDATES:
            rows[name].extend(pred[name])
        measured.extend(observation)
        decision = compatible_set(rows, measured, tolerance.radius, equivalence_groups)
        native = compatible_set({"native": native_prediction(case)}, observation, tolerance.radius)
        trajectory.append(dict(case_id=case.case_id, stage=case.stage,
                               retained_before=retained, retained_after=decision["retained"],
                               outcome=decision["outcome"], retained_groups=decision["retained_groups"],
                               predictions=pred, observation=observation,
                               native_null_compatible=bool(native["retained"]),
                               scientific_tolerance=tolerance.scientific_tolerance,
                               numeric_allowance=tolerance.numeric_allowance, radius=tolerance.radius))
        retained = decision["retained"]
    return trajectory
